### ISSUE TITLE
Please tag all Play Store releases. The latest Android version 4.10.0 is not tagged unambigously.

### ISSUE THREAD

**Issue by Giszmo** [breadwallet/brd-mobile#1]
I'm looking for the exact code that went into update 4.10.0 of your app on Google Play but can't find a matching tag. I suspect it's d17d80e (tagged android-4.10.0.5) or 29904d4 (branch merged to master).

BRD is listed on WalletScrutiny.com and currently categorized as "nosource" following [some communication issues](https://github.com/breadwallet/breadwallet-android/issues/117).

I will revert to the "nonverifiable" verdict for now and also hope you reconsider the threats a non-reproducible build means to your millions of users and make it reproducible but we will probably also define standards for "nonverifiable" apps that require a clear match between release version name and git tags to avoid requiring guessing.

**Comment by Giszmo** [comment]
The ios version has the same issue with the tag being ios-4.11.0.13 which probably is supposed to match the iPhone release 4.11.

In both cases, also tagging it android-4.10 and ios-4.11 respectively would be a commitment to not release minor updates with this version number.

**Comment by DrewCarlson** [comment]
The final release tags are now available as you've described.
