### ISSUE TITLE
What derivation path is used? 

### ISSUE THREAD

**Issue by Markeli** [breadwallet/brd-mobile#16]
Hi there!

Blockchain.info uses `m/44'/0'/0'` derivation path for their wallet. What derivation path do you use?

**Comment by kn0wmad** [comment]
Whoever is monitoring issues here doesn't know what this means.  See #24

Enraging...

**Comment by ewerx** [comment]
`m/0'/0`

**Comment by Markeli** [comment]
Thanks a lot!
