### ISSUE TITLE
Bitcoin excluded from wallet export

### ISSUE THREAD

**Issue by schmijos** [breadwallet/brd-mobile#22]
I've got a wallet with Tezos, Ether and Bitcoin. While I was able to restore Tezos and Ether in the AirGap Vault app, Bitcoin don't show up. They also didn't show up in the Coinbase wallet.

While the transaction history clearly shows Bitcoin in my BRD wallet, the wallet secret doesn't seem to include them. How is this possible? Can I somehow debug my wallet configuration?

**Comment by shivangigandhi** [comment]
Hi @schmijos, 

What version of Coinbase Wallet are you using? We're rolling out Android 26.7 and iOS 24.14 this week which should resolve your issues on previous versions. 

Also make sure that Settings > Advanced Settings > Toggle BRD BTC Scanning is enabled (should be on by default)

**Comment by shivangigandhi** [comment]
To pelkin7:

Reply to your comments which you may have deleted in error or on purpose:
_"Hi I just try to access my IOS app and it forced me to migrate to coin base wallet , BTC was migrated but only one transaction others I see when I download trans civ but not in Coinbase wallet ... Any ideas how to fixed ?"_

AND

_"I have installed Android app and it worked , but not in IOS"_

Can you share the versions that you are using for Coinbase Wallet if there is still an error?  Thanks!

**Comment by pelkin7** [comment]
Hi All is good now once I have enabled BRD BTC Scanning in both android and IOS , Thanks

**Comment by schmijos** [comment]
Hi there it's ok for me now as well. It took ages to "scan". Whatever that means.

**Comment by shivangigandhi** [comment]
Excellent glad to hear! 

It means that it has to scan the entire blockchain looking for your transactions :). The older wallets take longer. 

Thanks for your continued support!
